package view;

import javax.swing.table.TableRowSorter;
import Model.*;
import DAO.*;
import Connection.*;
import com.mysql.cj.jdbc.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import Ordenação.*;

public class CronosStart1 extends javax.swing.JFrame {

    private static void setRowSorter(TableRowSorter tableRowSorter) {
    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public FileInputStream fisL;
    private int tam2;
    
    public CronosStart1() {
       
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tResultado.getModel();
        tResultado.setRowSorter(new TableRowSorter (modelo));
        readJTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtRegistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lFoto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bCadAtt = new javax.swing.JButton();
        bCad = new javax.swing.JButton();
        bCadDel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tResultado = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtPesquisa = new javax.swing.JTextField();
        bBinaria = new javax.swing.JButton();
        bLinear = new javax.swing.JButton();
        bSelect = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bPilha = new javax.swing.JButton();
        bFila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronos Start");
        setLocation(new java.awt.Point(500, 10));
        setPreferredSize(new java.awt.Dimension(850, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 700));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(227, 227, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setText("Registro");
        jLabel1.setToolTipText("");

        TxtRegistro.setToolTipText("Identificação (vazio para cadastrar)");

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel2.setText("Nome");
        jLabel2.setToolTipText("");

        TxtNome.setToolTipText("Nome do registro");

        jButton2.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9215082_add_plus_box_addition_button_icon.png"))); // NOI18N
        jButton2.setToolTipText("Adicionar imagem");
        jButton2.setPreferredSize(new java.awt.Dimension(64, 64));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TxtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        lFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7312707_foto_media_photo_picture_image_icon (1).png"))); // NOI18N
        lFoto.setPreferredSize(new java.awt.Dimension(256, 256));

        jPanel3.setBackground(new java.awt.Color(227, 227, 227));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bCadAtt.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        bCadAtt.setText("Atualizar");
        bCadAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadAttActionPerformed(evt);
            }
        });

        bCad.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        bCad.setText("Cadastrar");
        bCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadActionPerformed(evt);
            }
        });

        bCadDel.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        bCadDel.setText("Excluir");
        bCadDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bCad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(bCadAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bCadDel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCadAtt)
                    .addComponent(bCadDel)
                    .addComponent(bCad))
                .addContainerGap())
        );

        tResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registro", "Nome", "Imagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tResultado);

        jPanel4.setBackground(new java.awt.Color(227, 227, 227));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setText("Pesquisa por Registro");

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel4.setText("Informe o registro que deseja buscar ");

        bBinaria.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        bBinaria.setText("Binaria");
        bBinaria.setToolTipText("Pesquisa Binaria");
        bBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBinariaActionPerformed(evt);
            }
        });

        bLinear.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        bLinear.setText("Linear");
        bLinear.setToolTipText("Pequisa Linear");
        bLinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLinearActionPerformed(evt);
            }
        });

        bSelect.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        bSelect.setText("Select");
        bSelect.setToolTipText("Seleciona direto do banco");
        bSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(TxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bBinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bLinear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBinaria)
                    .addComponent(bLinear)
                    .addComponent(bSelect))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(227, 227, 227));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel5.setText("Ordenação");
        jLabel5.setToolTipText("");

        bPilha.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        bPilha.setText("Pilha");
        bPilha.setToolTipText("Pequisa Linear");
        bPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPilhaActionPerformed(evt);
            }
        });

        bFila.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        bFila.setText("Fila");
        bFila.setToolTipText("Pequisa Linear");
        bFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bPilha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bPilha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFila)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCadAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadAttActionPerformed
        // TODO add your handling code here:
        ListaP L = new ListaP();
        ListaPDAO dao = new ListaPDAO();
        L.setRegistro(Integer.parseInt(TxtRegistro.getText()));
        L.setNome(TxtNome.getText());
        L.setFis(fisL);
        L.setTam(tam2);
        
        dao.update(L);
        
        TxtRegistro.setText("");
        TxtNome.setText("");
        lFoto.setIcon(null);
        readJTable();
    }//GEN-LAST:event_bCadAttActionPerformed

    private void bCadDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadDelActionPerformed
        // TODO add your handling code here:
        ListaP L = new ListaP();
        ListaPDAO dao = new ListaPDAO();
        L.setRegistro(Integer.parseInt(TxtRegistro.getText()));
        dao.delete(L);
        readJTable();
    }//GEN-LAST:event_bCadDelActionPerformed

    private void bCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadActionPerformed
        // TODO add your handling code here:
        ListaP L = new ListaP();
        ListaPDAO dao = new ListaPDAO();
        //L.setRegistro(Integer.parseInt(TxtRegistro.getText()));
        L.setNome(TxtNome.getText());
        L.setFis(fisL);
        L.setTam(tam2);
        
        dao.create(L);
        
        TxtRegistro.setText("");
        TxtNome.setText("");
        lFoto.setIcon(null);
        readJTable();
    }//GEN-LAST:event_bCadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Selecionar arquivo");
        jfc.setFileFilter(new FileNameExtensionFilter("Arquivo de imagens (*.PNG,*.JPG,*.JPEG)", "png", "jpg", "jpeg"));
        int result = jfc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                            FileInputStream fis1 = new FileInputStream(jfc.getSelectedFile());
                            fisL = fis1;
                            int tam1 = (int) jfc.getSelectedFile().length();
                            tam2 = tam1;
				Image foto = ImageIO.read(jfc.getSelectedFile()).getScaledInstance(lFoto.getWidth(),
						lFoto.getHeight(), Image.SCALE_SMOOTH);
				lFoto.setIcon(new ImageIcon(foto));
				lFoto.updateUI();
				//fotoCarregada = true;
			} catch (Exception e) {
				System.out.println(e);
			}
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBinariaActionPerformed
        // TODO add your handling code here:
       int x = Integer.parseInt(TxtPesquisa.getText());
       int inicio = 0, fim = tResultado.getRowCount()-1;
       long iniciar = System.currentTimeMillis();
       int meio;
           
       while (inicio <= fim) {
           meio = (inicio + fim) / 2;
           
           if (x == Integer.parseInt(tResultado.getValueAt(meio, 0).toString())){
               long fi = System.currentTimeMillis();

               JOptionPane.showMessageDialog(null, "Valor encontrado na posição "+meio+"/n Tempo de pesquisa "+(iniciar - fi)+"ms");
           }
           if (x < Integer.parseInt(tResultado.getValueAt(meio, 0).toString())){
               fim = meio - 1;
               System.out.println(Integer.parseInt(tResultado.getValueAt(meio, 0).toString()));
           }else{
               inicio = meio + 1;
           }
       }
    }//GEN-LAST:event_bBinariaActionPerformed

    private void bLinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLinearActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(TxtPesquisa.getText());
        int n = tResultado.getRowCount();
        long iniciar = System.currentTimeMillis();
        for (int i = 0; i < n; i++)
            if (x == Integer.parseInt(tResultado.getValueAt(i, 0).toString())){
                long fi = System.currentTimeMillis();
                JOptionPane.showMessageDialog(null, "Valor encontrado na posição "+i+"/n Tempo de pesquisa "+(iniciar - fi)+"ms");
            }


    }//GEN-LAST:event_bLinearActionPerformed

    private void bSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelectActionPerformed
        // TODO add your handling code here:
        ListaPDAO dao = new ListaPDAO();
        ListaP P = new ListaP();
        P.setRegistro(Integer.parseInt(TxtPesquisa.getText()));
        long iniciar = System.currentTimeMillis();
        dao.select(P);
        //TxtNome.setText(P.getNome());
        TxtNome.setText(dao.select(P).getNome());
        BufferedImage imagem = null;
        try{
            imagem = ImageIO.read(new ByteArrayInputStream(dao.select(P).getImg()));
        }catch(Exception e) {
            
        }
        ImageIcon icon = new ImageIcon(imagem);
        Icon foto = new ImageIcon(icon.getImage().getScaledInstance(lFoto.getWidth(), lFoto.getHeight(), Image.SCALE_SMOOTH));
        lFoto.setIcon(foto);
        TxtRegistro.setText(TxtPesquisa.getText());
        long fi = System.currentTimeMillis();
        JOptionPane.showMessageDialog(null, "Valor encontrado /n Tempo de pesquisa "+(iniciar -fi)+"ms");
    }//GEN-LAST:event_bSelectActionPerformed

    private void bPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPilhaActionPerformed
        // TODO add your handling code here:
        ListaPDAO cdao = new ListaPDAO();
        ListaP obj = new ListaP();
        long iniciar = System.currentTimeMillis();
        PilhaM ord = new PilhaM(tResultado.getRowCount());
            for (ListaP c: cdao.read()){                        
                ord.empilhar(c.getRegistro(), c.getNome(), c.getImg());
                
            }
        long fi = System.currentTimeMillis();
        ord.exibePilha();
        JOptionPane.showMessageDialog(null, "Ordenação completa /n Tempo de ordenação "+(iniciar -fi)+"ms");
    }//GEN-LAST:event_bPilhaActionPerformed

    private void bFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFilaActionPerformed
        // TODO add your handling code here:
        ListaPDAO cdao = new ListaPDAO();
        ListaP obj = new ListaP();
        long iniciar = System.currentTimeMillis();
        FilaM ord = new FilaM(tResultado.getRowCount());
            for (ListaP c: cdao.read()){                        
                ord.enfileirar(c.getRegistro(), c.getNome(), c.getImg());
                
            }
        long fi = System.currentTimeMillis();
        ord.exibeFila();
        JOptionPane.showMessageDialog(null, "Ordenação completa /n Tempo de ordenação "+(iniciar -fi)+"ms");
    }//GEN-LAST:event_bFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CronosStart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CronosStart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CronosStart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CronosStart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CronosStart1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtPesquisa;
    private javax.swing.JTextField TxtRegistro;
    private javax.swing.JButton bBinaria;
    private javax.swing.JButton bCad;
    private javax.swing.JButton bCadAtt;
    private javax.swing.JButton bCadDel;
    private javax.swing.JButton bFila;
    private javax.swing.JButton bLinear;
    private javax.swing.JButton bPilha;
    private javax.swing.JButton bSelect;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lFoto;
    private javax.swing.JTable tResultado;
    // End of variables declaration//GEN-END:variables

    private void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) tResultado.getModel();
        modelo.setNumRows(0);
        ListaPDAO cdao = new ListaPDAO();
        for (ListaP c: cdao.read()){
            modelo.addRow(new Object[]{
                c.getRegistro(),
                c.getNome(),
                c.getImg(),
            });
            
        }
    }
}
